### ISSUE TITLE
Base wrapper

### ISSUE THREAD

**Issue by fullstackfool** [karnama/vueish#108]
Investigate a base wrapper to improve DRY in the components

**Comment by nandi95** [comment]
Can you elaborate on this? What would be DRY-ed up?
This is almost a year old, is this going to be actioned?

**Comment by fullstackfool** [comment]
> Can you elaborate on this? What would be DRY-ed up? This is almost a year old, is this going to be actioned?

6? Definitely 6.

In all seriouness I believe this may have been in reference to dry-ing up the different inputs, but given the composables is no longer needed.
