### ISSUE TITLE
UIPanel: component should not implement <main> tag.

### ISSUE THREAD

**Issue by fullstackfool** [karnama/vueish#403]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

https://github.com/karnama/vueish/blob/8a2821873c72525e97553b61f19b9a9aaa5f99dc/src/components/panel/UIPanel.vue#L35-L37

**Comment by fullstackfool** [comment]
Or `<section>`, if we expect the body to host multiple chunks of content that differ in focus.

**Comment by nandi95** [comment]
The modal's root element is already a section though.

So it should be either the root being an article which have sub sections (that would require the dev to use article in the slot for semantic correctness, or this could be article where has more freedom while being more semantically correct.
Ideally all parts of the body should be related in focus.

**Comment by fullstackfool** [comment]
From the spec for `article`:

> The article element represents a component of a page that consists of a self-contained composition in a document, page, application, or site and that is intended to be independently distributable or reusable, e.g. in syndication. This could be a forum post, a magazine or newspaper article, a blog entry, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

I think I would say that the content of a modal almost always links to the main document, it's not really self-contained or independent.

So maybe just a `div`? Better to have a generalised semantic tag than a narrow, incorrect one?

**Comment by nandi95** [comment]
I think that would be the best, yeah.
