### ISSUE TITLE
UIInput suffix overflows on small input size.

### ISSUE THREAD

**Issue by deniskoronets** [karnama/vueish#430]
![image](https://user-images.githubusercontent.com/5627329/157870913-9b8c52c1-9108-4722-8c4a-d95c14a82c6a.png)
In case of width around less than 17rem.
I assume that <input> element should have some min-width property and hide prefix/suffix on smaller width.

**Comment by nandi95** [comment]
https://user-images.githubusercontent.com/41805560/158010040-ef6c1bde-adc0-4dcf-8196-d15ae7bba4ac.mov

It playes quite reasonable on the demo board.
Are there some styling in your app that causes this?
Might need some replication steps if no.

**Comment by deniskoronets** [comment]
![image](https://user-images.githubusercontent.com/5627329/161267762-8a12817e-8a70-4693-8077-28e8a8be7773.png)
After vueish update I've got it working properly as expected.
